/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MentorRouteImport } from './routes/_mentor'
import { Route as LearnerRouteImport } from './routes/_learner'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as LearnerDashboardRouteImport } from './routes/_learner/dashboard'
import { Route as LearnerProjectsIndexRouteImport } from './routes/_learner/projects/index'
import { Route as LearnerCoursesIndexRouteImport } from './routes/_learner/courses/index'
import { Route as LearnerChallengesIndexRouteImport } from './routes/_learner/challenges/index'
import { Route as AdminAdminIndexRouteImport } from './routes/_admin/admin/index'
import { Route as MentorMentorDashboardRouteImport } from './routes/_mentor/mentor/dashboard'
import { Route as LearnerProjectsNewRouteImport } from './routes/_learner/projects/new'
import { Route as LearnerCoursesCourseIdRouteImport } from './routes/_learner/courses/$courseId'
import { Route as LearnerChallengesChallengeIdRouteImport } from './routes/_learner/challenges/$challengeId'
import { Route as AdminAdminUsersRouteImport } from './routes/_admin/admin/users'
import { Route as AdminAdminSettingsRouteImport } from './routes/_admin/admin/settings'
import { Route as AdminAdminCoursesRouteImport } from './routes/_admin/admin/courses'
import { Route as AdminAdminChallengesRouteImport } from './routes/_admin/admin/challenges'
import { Route as AdminAdminAnalyticsRouteImport } from './routes/_admin/admin/analytics'
import { Route as MentorMentorReviewsProjectIdRouteImport } from './routes/_mentor/mentor/reviews/$projectId'

const MentorRoute = MentorRouteImport.update({
  id: '/_mentor',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnerRoute = LearnerRouteImport.update({
  id: '/_learner',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnerDashboardRoute = LearnerDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => LearnerRoute,
} as any)
const LearnerProjectsIndexRoute = LearnerProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => LearnerRoute,
} as any)
const LearnerCoursesIndexRoute = LearnerCoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => LearnerRoute,
} as any)
const LearnerChallengesIndexRoute = LearnerChallengesIndexRouteImport.update({
  id: '/challenges/',
  path: '/challenges/',
  getParentRoute: () => LearnerRoute,
} as any)
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AdminRoute,
} as any)
const MentorMentorDashboardRoute = MentorMentorDashboardRouteImport.update({
  id: '/mentor/dashboard',
  path: '/mentor/dashboard',
  getParentRoute: () => MentorRoute,
} as any)
const LearnerProjectsNewRoute = LearnerProjectsNewRouteImport.update({
  id: '/projects/new',
  path: '/projects/new',
  getParentRoute: () => LearnerRoute,
} as any)
const LearnerCoursesCourseIdRoute = LearnerCoursesCourseIdRouteImport.update({
  id: '/courses/$courseId',
  path: '/courses/$courseId',
  getParentRoute: () => LearnerRoute,
} as any)
const LearnerChallengesChallengeIdRoute =
  LearnerChallengesChallengeIdRouteImport.update({
    id: '/challenges/$challengeId',
    path: '/challenges/$challengeId',
    getParentRoute: () => LearnerRoute,
  } as any)
const AdminAdminUsersRoute = AdminAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminSettingsRoute = AdminAdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminCoursesRoute = AdminAdminCoursesRouteImport.update({
  id: '/admin/courses',
  path: '/admin/courses',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminChallengesRoute = AdminAdminChallengesRouteImport.update({
  id: '/admin/challenges',
  path: '/admin/challenges',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminAnalyticsRoute = AdminAdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const MentorMentorReviewsProjectIdRoute =
  MentorMentorReviewsProjectIdRouteImport.update({
    id: '/mentor/reviews/$projectId',
    path: '/mentor/reviews/$projectId',
    getParentRoute: () => MentorRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof LearnerDashboardRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/admin/analytics': typeof AdminAdminAnalyticsRoute
  '/admin/challenges': typeof AdminAdminChallengesRoute
  '/admin/courses': typeof AdminAdminCoursesRoute
  '/admin/settings': typeof AdminAdminSettingsRoute
  '/admin/users': typeof AdminAdminUsersRoute
  '/challenges/$challengeId': typeof LearnerChallengesChallengeIdRoute
  '/courses/$courseId': typeof LearnerCoursesCourseIdRoute
  '/projects/new': typeof LearnerProjectsNewRoute
  '/mentor/dashboard': typeof MentorMentorDashboardRoute
  '/admin': typeof AdminAdminIndexRoute
  '/challenges': typeof LearnerChallengesIndexRoute
  '/courses': typeof LearnerCoursesIndexRoute
  '/projects': typeof LearnerProjectsIndexRoute
  '/mentor/reviews/$projectId': typeof MentorMentorReviewsProjectIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof LearnerDashboardRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/admin/analytics': typeof AdminAdminAnalyticsRoute
  '/admin/challenges': typeof AdminAdminChallengesRoute
  '/admin/courses': typeof AdminAdminCoursesRoute
  '/admin/settings': typeof AdminAdminSettingsRoute
  '/admin/users': typeof AdminAdminUsersRoute
  '/challenges/$challengeId': typeof LearnerChallengesChallengeIdRoute
  '/courses/$courseId': typeof LearnerCoursesCourseIdRoute
  '/projects/new': typeof LearnerProjectsNewRoute
  '/mentor/dashboard': typeof MentorMentorDashboardRoute
  '/admin': typeof AdminAdminIndexRoute
  '/challenges': typeof LearnerChallengesIndexRoute
  '/courses': typeof LearnerCoursesIndexRoute
  '/projects': typeof LearnerProjectsIndexRoute
  '/mentor/reviews/$projectId': typeof MentorMentorReviewsProjectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/_learner': typeof LearnerRouteWithChildren
  '/_mentor': typeof MentorRouteWithChildren
  '/_learner/dashboard': typeof LearnerDashboardRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/_admin/admin/analytics': typeof AdminAdminAnalyticsRoute
  '/_admin/admin/challenges': typeof AdminAdminChallengesRoute
  '/_admin/admin/courses': typeof AdminAdminCoursesRoute
  '/_admin/admin/settings': typeof AdminAdminSettingsRoute
  '/_admin/admin/users': typeof AdminAdminUsersRoute
  '/_learner/challenges/$challengeId': typeof LearnerChallengesChallengeIdRoute
  '/_learner/courses/$courseId': typeof LearnerCoursesCourseIdRoute
  '/_learner/projects/new': typeof LearnerProjectsNewRoute
  '/_mentor/mentor/dashboard': typeof MentorMentorDashboardRoute
  '/_admin/admin/': typeof AdminAdminIndexRoute
  '/_learner/challenges/': typeof LearnerChallengesIndexRoute
  '/_learner/courses/': typeof LearnerCoursesIndexRoute
  '/_learner/projects/': typeof LearnerProjectsIndexRoute
  '/_mentor/mentor/reviews/$projectId': typeof MentorMentorReviewsProjectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/auth/login'
    | '/auth/register'
    | '/admin/analytics'
    | '/admin/challenges'
    | '/admin/courses'
    | '/admin/settings'
    | '/admin/users'
    | '/challenges/$challengeId'
    | '/courses/$courseId'
    | '/projects/new'
    | '/mentor/dashboard'
    | '/admin'
    | '/challenges'
    | '/courses'
    | '/projects'
    | '/mentor/reviews/$projectId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/auth/login'
    | '/auth/register'
    | '/admin/analytics'
    | '/admin/challenges'
    | '/admin/courses'
    | '/admin/settings'
    | '/admin/users'
    | '/challenges/$challengeId'
    | '/courses/$courseId'
    | '/projects/new'
    | '/mentor/dashboard'
    | '/admin'
    | '/challenges'
    | '/courses'
    | '/projects'
    | '/mentor/reviews/$projectId'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_learner'
    | '/_mentor'
    | '/_learner/dashboard'
    | '/auth/login'
    | '/auth/register'
    | '/_admin/admin/analytics'
    | '/_admin/admin/challenges'
    | '/_admin/admin/courses'
    | '/_admin/admin/settings'
    | '/_admin/admin/users'
    | '/_learner/challenges/$challengeId'
    | '/_learner/courses/$courseId'
    | '/_learner/projects/new'
    | '/_mentor/mentor/dashboard'
    | '/_admin/admin/'
    | '/_learner/challenges/'
    | '/_learner/courses/'
    | '/_learner/projects/'
    | '/_mentor/mentor/reviews/$projectId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LearnerRoute: typeof LearnerRouteWithChildren
  MentorRoute: typeof MentorRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_mentor': {
      id: '/_mentor'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof MentorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_learner': {
      id: '/_learner'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LearnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_learner/dashboard': {
      id: '/_learner/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof LearnerDashboardRouteImport
      parentRoute: typeof LearnerRoute
    }
    '/_learner/projects/': {
      id: '/_learner/projects/'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof LearnerProjectsIndexRouteImport
      parentRoute: typeof LearnerRoute
    }
    '/_learner/courses/': {
      id: '/_learner/courses/'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof LearnerCoursesIndexRouteImport
      parentRoute: typeof LearnerRoute
    }
    '/_learner/challenges/': {
      id: '/_learner/challenges/'
      path: '/challenges'
      fullPath: '/challenges'
      preLoaderRoute: typeof LearnerChallengesIndexRouteImport
      parentRoute: typeof LearnerRoute
    }
    '/_admin/admin/': {
      id: '/_admin/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_mentor/mentor/dashboard': {
      id: '/_mentor/mentor/dashboard'
      path: '/mentor/dashboard'
      fullPath: '/mentor/dashboard'
      preLoaderRoute: typeof MentorMentorDashboardRouteImport
      parentRoute: typeof MentorRoute
    }
    '/_learner/projects/new': {
      id: '/_learner/projects/new'
      path: '/projects/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof LearnerProjectsNewRouteImport
      parentRoute: typeof LearnerRoute
    }
    '/_learner/courses/$courseId': {
      id: '/_learner/courses/$courseId'
      path: '/courses/$courseId'
      fullPath: '/courses/$courseId'
      preLoaderRoute: typeof LearnerCoursesCourseIdRouteImport
      parentRoute: typeof LearnerRoute
    }
    '/_learner/challenges/$challengeId': {
      id: '/_learner/challenges/$challengeId'
      path: '/challenges/$challengeId'
      fullPath: '/challenges/$challengeId'
      preLoaderRoute: typeof LearnerChallengesChallengeIdRouteImport
      parentRoute: typeof LearnerRoute
    }
    '/_admin/admin/users': {
      id: '/_admin/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminAdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/settings': {
      id: '/_admin/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminAdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/courses': {
      id: '/_admin/admin/courses'
      path: '/admin/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AdminAdminCoursesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/challenges': {
      id: '/_admin/admin/challenges'
      path: '/admin/challenges'
      fullPath: '/admin/challenges'
      preLoaderRoute: typeof AdminAdminChallengesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/analytics': {
      id: '/_admin/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_mentor/mentor/reviews/$projectId': {
      id: '/_mentor/mentor/reviews/$projectId'
      path: '/mentor/reviews/$projectId'
      fullPath: '/mentor/reviews/$projectId'
      preLoaderRoute: typeof MentorMentorReviewsProjectIdRouteImport
      parentRoute: typeof MentorRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAdminAnalyticsRoute: typeof AdminAdminAnalyticsRoute
  AdminAdminChallengesRoute: typeof AdminAdminChallengesRoute
  AdminAdminCoursesRoute: typeof AdminAdminCoursesRoute
  AdminAdminSettingsRoute: typeof AdminAdminSettingsRoute
  AdminAdminUsersRoute: typeof AdminAdminUsersRoute
  AdminAdminIndexRoute: typeof AdminAdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminAnalyticsRoute: AdminAdminAnalyticsRoute,
  AdminAdminChallengesRoute: AdminAdminChallengesRoute,
  AdminAdminCoursesRoute: AdminAdminCoursesRoute,
  AdminAdminSettingsRoute: AdminAdminSettingsRoute,
  AdminAdminUsersRoute: AdminAdminUsersRoute,
  AdminAdminIndexRoute: AdminAdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface LearnerRouteChildren {
  LearnerDashboardRoute: typeof LearnerDashboardRoute
  LearnerChallengesChallengeIdRoute: typeof LearnerChallengesChallengeIdRoute
  LearnerCoursesCourseIdRoute: typeof LearnerCoursesCourseIdRoute
  LearnerProjectsNewRoute: typeof LearnerProjectsNewRoute
  LearnerChallengesIndexRoute: typeof LearnerChallengesIndexRoute
  LearnerCoursesIndexRoute: typeof LearnerCoursesIndexRoute
  LearnerProjectsIndexRoute: typeof LearnerProjectsIndexRoute
}

const LearnerRouteChildren: LearnerRouteChildren = {
  LearnerDashboardRoute: LearnerDashboardRoute,
  LearnerChallengesChallengeIdRoute: LearnerChallengesChallengeIdRoute,
  LearnerCoursesCourseIdRoute: LearnerCoursesCourseIdRoute,
  LearnerProjectsNewRoute: LearnerProjectsNewRoute,
  LearnerChallengesIndexRoute: LearnerChallengesIndexRoute,
  LearnerCoursesIndexRoute: LearnerCoursesIndexRoute,
  LearnerProjectsIndexRoute: LearnerProjectsIndexRoute,
}

const LearnerRouteWithChildren =
  LearnerRoute._addFileChildren(LearnerRouteChildren)

interface MentorRouteChildren {
  MentorMentorDashboardRoute: typeof MentorMentorDashboardRoute
  MentorMentorReviewsProjectIdRoute: typeof MentorMentorReviewsProjectIdRoute
}

const MentorRouteChildren: MentorRouteChildren = {
  MentorMentorDashboardRoute: MentorMentorDashboardRoute,
  MentorMentorReviewsProjectIdRoute: MentorMentorReviewsProjectIdRoute,
}

const MentorRouteWithChildren =
  MentorRoute._addFileChildren(MentorRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LearnerRoute: LearnerRouteWithChildren,
  MentorRoute: MentorRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
